version: '3.3'

services:
    db:
        image: mysql:5.7.22
        container_name: serverdb
        command: --sql_mode=""
        restart: always
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        ports:
            - "13306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9000 remote_enable=1
        ports:
            - '80:80'
        volumes:
            - './web:/var/www/html'
        depends_on:
            - db
